# Generated by Django 3.2.16 on 2022-12-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='has_children',
            field=models.BooleanField(null=True),
        ),
    ]
